apiVersion: v1
kind: Service
metadata:
  name: forge-gateway
  namespace: forge-system
  labels:
    app.kubernetes.io/name: forge-gateway
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: forge-gateway
  ports:
    - name: http
      port: 9000
      targetPort: http
